// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
// Triangle	 	    Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.
// Answer: 1533776805

module Problem45

let T n =
    (n * (n + 1L)) / 2L

let P n =
    (n * (3L * n - 1L )) / 2L

let H n =
    n * (2L * n -  1L)

let tph n = 
    let mutable run : bool = true
    let mutable nH : int64 = n
    let mutable value : int64 = 0L
    while run do
        nH <- nH + 1L
        value <- H nH
        let mutable nT : int64 = nH
        let mutable nP : int64 = nH
        let mutable newP : int64 = P nP
        while newP < value do
            newP <- P nP
            nP <- nP + 1L
        let mutable newT : int64 = T nT
        while newT < value do
            newT <- T nT
            nT <- nT + 1L
        if value = newT && value = newP then
            run <- false
    value